name: release-pr

on:
  pull_request:
    branches:
      - prod*
      - main*
      - master*
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch-for-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch starts with MEP, RELEASE or HOTFIX
        run-name: Check if source branch starts with MEP, RELEASE or HOTFIX
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: TARGET_BRANCH"
          
          if [[ ! "$SOURCE_BRANCH" =~ ^(MEP|RELEASE|HOTFIX).* ]]; then
            echo "❌ ERREUR: Les Pull Requests vers $TARGET_BRANCH doivent provenir de branches commençant par 'MEP', 'RELEASE' ou 'HOTFIX'"
            echo "Branche source actuelle: $SOURCE_BRANCH"
            echo "Exemples de branches valides: MEP-hotfix, RELEASE-1.0, MEP123, RELEASE-2024-01"
            exit 1
          fi
          
          echo "✅ Nom de branche valide: $SOURCE_BRANCH"