name: ut-branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"


jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Update or Create Unit Test Branch
        run: |
          git status
