name: ut-branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"


jobs:
  ut-branch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update or Create Unit Test Branch
        run: |
          # Vérifier si la branche existe déjà localement ou en remote
          if git show-ref --verify --quiet refs/remotes/origin/daily-testing; then
            echo "Branch daily-testing exists, checking it out"
            git checkout daily-testing
            git pull origin daily-testing
          else
            echo "Creating new branch daily-testing"
            git checkout -b daily-testing
          fi
          
          # Merge ou rebase avec la branche par défaut
          git merge origin/${{ github.event.repository.default_branch }} --no-ff
          
          # Push la branche (créée ou mise à jour)
          git push origin daily-testing